<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('INTERRUPCIONES', 'schema_siod');

/**
 * BaseINTERRUPCIONES
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $num_f328
 * @property integer $nivel_sistema
 * @property integer $cod_sistema
 * @property timestamp $fecha_hora_ini
 * @property integer $kva_interrump
 * @property decimal $mvamin
 * @property integer $cod_causa
 * @property integer $distrito
 * @property integer $num_proposicion
 * @property string $trabajo_realizado
 * @property integer $climatologia
 * @property integer $num_roe
 * @property integer $num_averia
 * 
 * @method integer        getNumF328()           Returns the current record's "num_f328" value
 * @method integer        getNivelSistema()      Returns the current record's "nivel_sistema" value
 * @method integer        getCodSistema()        Returns the current record's "cod_sistema" value
 * @method timestamp      getFechaHoraIni()      Returns the current record's "fecha_hora_ini" value
 * @method integer        getKvaInterrump()      Returns the current record's "kva_interrump" value
 * @method decimal        getMvamin()            Returns the current record's "mvamin" value
 * @method integer        getCodCausa()          Returns the current record's "cod_causa" value
 * @method integer        getDistrito()          Returns the current record's "distrito" value
 * @method integer        getNumProposicion()    Returns the current record's "num_proposicion" value
 * @method string         getTrabajoRealizado()  Returns the current record's "trabajo_realizado" value
 * @method integer        getClimatologia()      Returns the current record's "climatologia" value
 * @method integer        getNumRoe()            Returns the current record's "num_roe" value
 * @method integer        getNumAveria()         Returns the current record's "num_averia" value
 * @method INTERRUPCIONES setNumF328()           Sets the current record's "num_f328" value
 * @method INTERRUPCIONES setNivelSistema()      Sets the current record's "nivel_sistema" value
 * @method INTERRUPCIONES setCodSistema()        Sets the current record's "cod_sistema" value
 * @method INTERRUPCIONES setFechaHoraIni()      Sets the current record's "fecha_hora_ini" value
 * @method INTERRUPCIONES setKvaInterrump()      Sets the current record's "kva_interrump" value
 * @method INTERRUPCIONES setMvamin()            Sets the current record's "mvamin" value
 * @method INTERRUPCIONES setCodCausa()          Sets the current record's "cod_causa" value
 * @method INTERRUPCIONES setDistrito()          Sets the current record's "distrito" value
 * @method INTERRUPCIONES setNumProposicion()    Sets the current record's "num_proposicion" value
 * @method INTERRUPCIONES setTrabajoRealizado()  Sets the current record's "trabajo_realizado" value
 * @method INTERRUPCIONES setClimatologia()      Sets the current record's "climatologia" value
 * @method INTERRUPCIONES setNumRoe()            Sets the current record's "num_roe" value
 * @method INTERRUPCIONES setNumAveria()         Sets the current record's "num_averia" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseINTERRUPCIONES extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('INTERRUPCIONES');
        $this->hasColumn('num_f328', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 7,
             ));
        $this->hasColumn('nivel_sistema', 'integer', 1, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cod_sistema', 'integer', 5, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('fecha_hora_ini', 'timestamp', 7, array(
             'notnull' => true,
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('kva_interrump', 'integer', 7, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('mvamin', 'decimal', 7, array(
             'notnull' => true,
             'type' => 'decimal',
             'length' => 7,
             ));
        $this->hasColumn('cod_causa', 'integer', 3, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('distrito', 'integer', 2, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('num_proposicion', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('trabajo_realizado', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('climatologia', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('num_roe', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('num_averia', 'integer', 9, array(
             'type' => 'integer',
             'length' => 9,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}