<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_UNIDAD_EQUIPO', 'schema_saf');

/**
 * BaseSAF_UNIDAD_EQUIPO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $departamento
 * @property string $nombre
 * @property string $correo
 * @property Doctrine_Collection $SAF_PERSONAL
 * @property Doctrine_Collection $SAF_COMP_UE
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getDepartamento() Returns the current record's "departamento" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getCorreo()       Returns the current record's "correo" value
 * @method Doctrine_Collection getSAFPERSONAL()  Returns the current record's "SAF_PERSONAL" collection
 * @method Doctrine_Collection getSAFCOMPUE()    Returns the current record's "SAF_COMP_UE" collection
 * @method SAF_UNIDAD_EQUIPO   setId()           Sets the current record's "id" value
 * @method SAF_UNIDAD_EQUIPO   setDepartamento() Sets the current record's "departamento" value
 * @method SAF_UNIDAD_EQUIPO   setNombre()       Sets the current record's "nombre" value
 * @method SAF_UNIDAD_EQUIPO   setCorreo()       Sets the current record's "correo" value
 * @method SAF_UNIDAD_EQUIPO   setSAFPERSONAL()  Sets the current record's "SAF_PERSONAL" collection
 * @method SAF_UNIDAD_EQUIPO   setSAFCOMPUE()    Sets the current record's "SAF_COMP_UE" collection
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_UNIDAD_EQUIPO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_UNIDAD_EQUIPO');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'SAF_UNIDAD_EQUIPO',
             ));
        $this->hasColumn('departamento', 'string', 10, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('correo', 'string', 50, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SAF_PERSONAL', array(
             'local' => 'id',
             'foreign' => 'id_ue'));

        $this->hasMany('SAF_COMP_UE', array(
             'local' => 'id',
             'foreign' => 'id_ue'));
    }
}