<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_EVENTO_RAZON', 'schema_saf');

/**
 * BaseSAF_EVENTO_RAZON
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_evento
 * @property integer $id_razon
 * @property integer $mva_min
 * @property SAF_EVENTO $SAF_EVENTO
 * @property SAF_RAZON_MVAMIN $SAF_RAZON_MVAMIN
 * 
 * @method integer          getIdEvento()         Returns the current record's "id_evento" value
 * @method integer          getIdRazon()          Returns the current record's "id_razon" value
 * @method integer          getMvaMin()           Returns the current record's "mva_min" value
 * @method SAF_EVENTO       getSAFEVENTO()        Returns the current record's "SAF_EVENTO" value
 * @method SAF_RAZON_MVAMIN getSAFRAZONMVAMIN()   Returns the current record's "SAF_RAZON_MVAMIN" value
 * @method SAF_EVENTO_RAZON setIdEvento()         Sets the current record's "id_evento" value
 * @method SAF_EVENTO_RAZON setIdRazon()          Sets the current record's "id_razon" value
 * @method SAF_EVENTO_RAZON setMvaMin()           Sets the current record's "mva_min" value
 * @method SAF_EVENTO_RAZON setSAFEVENTO()        Sets the current record's "SAF_EVENTO" value
 * @method SAF_EVENTO_RAZON setSAFRAZONMVAMIN()   Sets the current record's "SAF_RAZON_MVAMIN" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_EVENTO_RAZON extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_EVENTO_RAZON');
        $this->hasColumn('id_evento', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_razon', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('mva_min', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_EVENTO', array(
             'local' => 'id_evento',
             'foreign' => 'id'));

        $this->hasOne('SAF_RAZON_MVAMIN', array(
             'local' => 'id_razon',
             'foreign' => 'id'));
    }
}