<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AVERIA', 'schema_siod');

/**
 * BaseAVERIA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $num_averia
 * @property timestamp $fecha_origen
 * @property integer $distrito
 * @property string $descripcion
 * @property string $edo_averia
 * @property integer $compania
 * @property string $sector_afectado
 * @property integer $cod_nivel
 * @property integer $cod_sistema
 * @property integer $voltaje
 * @property string $cod_cuadricula
 * @property integer $cod_ubicacion
 * @property integer $duracion_maxima
 * @property integer $kva_interrump
 * @property integer $cod_material
 * @property integer $cod_causa
 * @property integer $ind_tipo_equipo
 * @property integer $cod_equipo
 * @property integer $ind_tipo_tramo
 * @property integer $cod_tramo
 * @property string $num_rec
 * @property string $cod_unidad_oper
 * @property decimal $mva_min
 * @property string $cod_oper_mesa
 * @property timestamp $hr_est_rest_serv
 * @property timestamp $fch_inicio
 * @property integer $cod_mesa
 * @property string $cod_oper_revisado
 * @property string $ind_reconocido
 * @property string $cond_registro
 * @property integer $ind_color
 * @property integer $mesa_actual
 * @property integer $tamano
 * @property integer $unidades
 * @property string $cod_marca
 * @property integer $tipo_falla
 * @property string $cod_oper_mesa_act
 * @property string $descripcion1
 * @property string $descripcion2
 * @property string $carga_recuperada
 * @property integer $kva_afect_actual
 * @property integer $cant_fases_afect
 * 
 * @method integer   getNumAveria()         Returns the current record's "num_averia" value
 * @method timestamp getFechaOrigen()       Returns the current record's "fecha_origen" value
 * @method integer   getDistrito()          Returns the current record's "distrito" value
 * @method string    getDescripcion()       Returns the current record's "descripcion" value
 * @method string    getEdoAveria()         Returns the current record's "edo_averia" value
 * @method integer   getCompania()          Returns the current record's "compania" value
 * @method string    getSectorAfectado()    Returns the current record's "sector_afectado" value
 * @method integer   getCodNivel()          Returns the current record's "cod_nivel" value
 * @method integer   getCodSistema()        Returns the current record's "cod_sistema" value
 * @method integer   getVoltaje()           Returns the current record's "voltaje" value
 * @method string    getCodCuadricula()     Returns the current record's "cod_cuadricula" value
 * @method integer   getCodUbicacion()      Returns the current record's "cod_ubicacion" value
 * @method integer   getDuracionMaxima()    Returns the current record's "duracion_maxima" value
 * @method integer   getKvaInterrump()      Returns the current record's "kva_interrump" value
 * @method integer   getCodMaterial()       Returns the current record's "cod_material" value
 * @method integer   getCodCausa()          Returns the current record's "cod_causa" value
 * @method integer   getIndTipoEquipo()     Returns the current record's "ind_tipo_equipo" value
 * @method integer   getCodEquipo()         Returns the current record's "cod_equipo" value
 * @method integer   getIndTipoTramo()      Returns the current record's "ind_tipo_tramo" value
 * @method integer   getCodTramo()          Returns the current record's "cod_tramo" value
 * @method string    getNumRec()            Returns the current record's "num_rec" value
 * @method string    getCodUnidadOper()     Returns the current record's "cod_unidad_oper" value
 * @method decimal   getMvaMin()            Returns the current record's "mva_min" value
 * @method string    getCodOperMesa()       Returns the current record's "cod_oper_mesa" value
 * @method timestamp getHrEstRestServ()     Returns the current record's "hr_est_rest_serv" value
 * @method timestamp getFchInicio()         Returns the current record's "fch_inicio" value
 * @method integer   getCodMesa()           Returns the current record's "cod_mesa" value
 * @method string    getCodOperRevisado()   Returns the current record's "cod_oper_revisado" value
 * @method string    getIndReconocido()     Returns the current record's "ind_reconocido" value
 * @method string    getCondRegistro()      Returns the current record's "cond_registro" value
 * @method integer   getIndColor()          Returns the current record's "ind_color" value
 * @method integer   getMesaActual()        Returns the current record's "mesa_actual" value
 * @method integer   getTamano()            Returns the current record's "tamano" value
 * @method integer   getUnidades()          Returns the current record's "unidades" value
 * @method string    getCodMarca()          Returns the current record's "cod_marca" value
 * @method integer   getTipoFalla()         Returns the current record's "tipo_falla" value
 * @method string    getCodOperMesaAct()    Returns the current record's "cod_oper_mesa_act" value
 * @method string    getDescripcion1()      Returns the current record's "descripcion1" value
 * @method string    getDescripcion2()      Returns the current record's "descripcion2" value
 * @method string    getCargaRecuperada()   Returns the current record's "carga_recuperada" value
 * @method integer   getKvaAfectActual()    Returns the current record's "kva_afect_actual" value
 * @method integer   getCantFasesAfect()    Returns the current record's "cant_fases_afect" value
 * @method AVERIA    setNumAveria()         Sets the current record's "num_averia" value
 * @method AVERIA    setFechaOrigen()       Sets the current record's "fecha_origen" value
 * @method AVERIA    setDistrito()          Sets the current record's "distrito" value
 * @method AVERIA    setDescripcion()       Sets the current record's "descripcion" value
 * @method AVERIA    setEdoAveria()         Sets the current record's "edo_averia" value
 * @method AVERIA    setCompania()          Sets the current record's "compania" value
 * @method AVERIA    setSectorAfectado()    Sets the current record's "sector_afectado" value
 * @method AVERIA    setCodNivel()          Sets the current record's "cod_nivel" value
 * @method AVERIA    setCodSistema()        Sets the current record's "cod_sistema" value
 * @method AVERIA    setVoltaje()           Sets the current record's "voltaje" value
 * @method AVERIA    setCodCuadricula()     Sets the current record's "cod_cuadricula" value
 * @method AVERIA    setCodUbicacion()      Sets the current record's "cod_ubicacion" value
 * @method AVERIA    setDuracionMaxima()    Sets the current record's "duracion_maxima" value
 * @method AVERIA    setKvaInterrump()      Sets the current record's "kva_interrump" value
 * @method AVERIA    setCodMaterial()       Sets the current record's "cod_material" value
 * @method AVERIA    setCodCausa()          Sets the current record's "cod_causa" value
 * @method AVERIA    setIndTipoEquipo()     Sets the current record's "ind_tipo_equipo" value
 * @method AVERIA    setCodEquipo()         Sets the current record's "cod_equipo" value
 * @method AVERIA    setIndTipoTramo()      Sets the current record's "ind_tipo_tramo" value
 * @method AVERIA    setCodTramo()          Sets the current record's "cod_tramo" value
 * @method AVERIA    setNumRec()            Sets the current record's "num_rec" value
 * @method AVERIA    setCodUnidadOper()     Sets the current record's "cod_unidad_oper" value
 * @method AVERIA    setMvaMin()            Sets the current record's "mva_min" value
 * @method AVERIA    setCodOperMesa()       Sets the current record's "cod_oper_mesa" value
 * @method AVERIA    setHrEstRestServ()     Sets the current record's "hr_est_rest_serv" value
 * @method AVERIA    setFchInicio()         Sets the current record's "fch_inicio" value
 * @method AVERIA    setCodMesa()           Sets the current record's "cod_mesa" value
 * @method AVERIA    setCodOperRevisado()   Sets the current record's "cod_oper_revisado" value
 * @method AVERIA    setIndReconocido()     Sets the current record's "ind_reconocido" value
 * @method AVERIA    setCondRegistro()      Sets the current record's "cond_registro" value
 * @method AVERIA    setIndColor()          Sets the current record's "ind_color" value
 * @method AVERIA    setMesaActual()        Sets the current record's "mesa_actual" value
 * @method AVERIA    setTamano()            Sets the current record's "tamano" value
 * @method AVERIA    setUnidades()          Sets the current record's "unidades" value
 * @method AVERIA    setCodMarca()          Sets the current record's "cod_marca" value
 * @method AVERIA    setTipoFalla()         Sets the current record's "tipo_falla" value
 * @method AVERIA    setCodOperMesaAct()    Sets the current record's "cod_oper_mesa_act" value
 * @method AVERIA    setDescripcion1()      Sets the current record's "descripcion1" value
 * @method AVERIA    setDescripcion2()      Sets the current record's "descripcion2" value
 * @method AVERIA    setCargaRecuperada()   Sets the current record's "carga_recuperada" value
 * @method AVERIA    setKvaAfectActual()    Sets the current record's "kva_afect_actual" value
 * @method AVERIA    setCantFasesAfect()    Sets the current record's "cant_fases_afect" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAVERIA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('AVERIA');
        $this->hasColumn('num_averia', 'integer', 9, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 9,
             ));
        $this->hasColumn('fecha_origen', 'timestamp', 7, array(
             'notnull' => true,
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('distrito', 'integer', 2, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('edo_averia', 'string', 2, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('compania', 'integer', 2, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('sector_afectado', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cod_nivel', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('cod_sistema', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('voltaje', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('cod_cuadricula', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('cod_ubicacion', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('duracion_maxima', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('kva_interrump', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('cod_material', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('cod_causa', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('ind_tipo_equipo', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cod_equipo', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('ind_tipo_tramo', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cod_tramo', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('num_rec', 'string', 12, array(
             'type' => 'string',
             'length' => 12,
             ));
        $this->hasColumn('cod_unidad_oper', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('mva_min', 'decimal', 7, array(
             'type' => 'decimal',
             'length' => 7,
             ));
        $this->hasColumn('cod_oper_mesa', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('hr_est_rest_serv', 'timestamp', 7, array(
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('fch_inicio', 'timestamp', 7, array(
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('cod_mesa', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('cod_oper_revisado', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('ind_reconocido', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('cond_registro', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('ind_color', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('mesa_actual', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('tamano', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('unidades', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('cod_marca', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('tipo_falla', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('cod_oper_mesa_act', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('descripcion1', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('descripcion2', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('carga_recuperada', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('kva_afect_actual', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('cant_fases_afect', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}