<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_COMP_UE', 'schema_saf');

/**
 * BaseSAF_COMP_UE
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_compromiso
 * @property integer $id_ue
 * @property SAF_VARIO $SAF_VARIO
 * @property SAF_UNIDAD_EQUIPO $SAF_UNIDAD_EQUIPO
 * @property Doctrine_Collection $SAF_TAREA_REALIZADA_COMP
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method integer             getIdCompromiso()             Returns the current record's "id_compromiso" value
 * @method integer             getIdUe()                     Returns the current record's "id_ue" value
 * @method SAF_VARIO           getSAFVARIO()                 Returns the current record's "SAF_VARIO" value
 * @method SAF_UNIDAD_EQUIPO   getSAFUNIDADEQUIPO()          Returns the current record's "SAF_UNIDAD_EQUIPO" value
 * @method Doctrine_Collection getSAFTAREAREALIZADACOMP()    Returns the current record's "SAF_TAREA_REALIZADA_COMP" collection
 * @method SAF_COMP_UE         setId()                       Sets the current record's "id" value
 * @method SAF_COMP_UE         setIdCompromiso()             Sets the current record's "id_compromiso" value
 * @method SAF_COMP_UE         setIdUe()                     Sets the current record's "id_ue" value
 * @method SAF_COMP_UE         setSAFVARIO()                 Sets the current record's "SAF_VARIO" value
 * @method SAF_COMP_UE         setSAFUNIDADEQUIPO()          Sets the current record's "SAF_UNIDAD_EQUIPO" value
 * @method SAF_COMP_UE         setSAFTAREAREALIZADACOMP()    Sets the current record's "SAF_TAREA_REALIZADA_COMP" collection
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_COMP_UE extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_COMP_UE');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'SAF_COMP_UE',
             ));
        $this->hasColumn('id_compromiso', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('id_ue', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_VARIO', array(
             'local' => 'id_compromiso',
             'foreign' => 'id'));

        $this->hasOne('SAF_UNIDAD_EQUIPO', array(
             'local' => 'id_ue',
             'foreign' => 'id'));

        $this->hasMany('SAF_TAREA_REALIZADA_COMP', array(
             'local' => 'id',
             'foreign' => 'id_comp_ue'));
    }
}