<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CRONOLOGIA', 'schema_siod');

/**
 * BaseCRONOLOGIA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $num_f328
 * @property timestamp $fecha_asig
 * @property string $resp_mesa_asig
 * @property string $resp_campo_asig
 * @property integer $kva_asig
 * @property timestamp $fecha_lleg
 * @property string $resp_mesa_lleg
 * @property string $resp_campo_lleg
 * @property timestamp $fecha_loc_grue
 * @property string $resp_mesa_loc_grue
 * @property string $resp_campo_loc_grue
 * @property integer $kva_loc_grue
 * @property timestamp $fecha_loc_fina
 * @property string $resp_mesa_loc_fina
 * @property string $resp_campo_loc_fina
 * @property integer $kva_loc_fina
 * @property timestamp $fecha_reparacion
 * @property string $resp_mesa_rep
 * @property string $resp_campo_rep
 * @property integer $kva_reparacion
 * 
 * @method integer    getNumF328()             Returns the current record's "num_f328" value
 * @method timestamp  getFechaAsig()           Returns the current record's "fecha_asig" value
 * @method string     getRespMesaAsig()        Returns the current record's "resp_mesa_asig" value
 * @method string     getRespCampoAsig()       Returns the current record's "resp_campo_asig" value
 * @method integer    getKvaAsig()             Returns the current record's "kva_asig" value
 * @method timestamp  getFechaLleg()           Returns the current record's "fecha_lleg" value
 * @method string     getRespMesaLleg()        Returns the current record's "resp_mesa_lleg" value
 * @method string     getRespCampoLleg()       Returns the current record's "resp_campo_lleg" value
 * @method timestamp  getFechaLocGrue()        Returns the current record's "fecha_loc_grue" value
 * @method string     getRespMesaLocGrue()     Returns the current record's "resp_mesa_loc_grue" value
 * @method string     getRespCampoLocGrue()    Returns the current record's "resp_campo_loc_grue" value
 * @method integer    getKvaLocGrue()          Returns the current record's "kva_loc_grue" value
 * @method timestamp  getFechaLocFina()        Returns the current record's "fecha_loc_fina" value
 * @method string     getRespMesaLocFina()     Returns the current record's "resp_mesa_loc_fina" value
 * @method string     getRespCampoLocFina()    Returns the current record's "resp_campo_loc_fina" value
 * @method integer    getKvaLocFina()          Returns the current record's "kva_loc_fina" value
 * @method timestamp  getFechaReparacion()     Returns the current record's "fecha_reparacion" value
 * @method string     getRespMesaRep()         Returns the current record's "resp_mesa_rep" value
 * @method string     getRespCampoRep()        Returns the current record's "resp_campo_rep" value
 * @method integer    getKvaReparacion()       Returns the current record's "kva_reparacion" value
 * @method CRONOLOGIA setNumF328()             Sets the current record's "num_f328" value
 * @method CRONOLOGIA setFechaAsig()           Sets the current record's "fecha_asig" value
 * @method CRONOLOGIA setRespMesaAsig()        Sets the current record's "resp_mesa_asig" value
 * @method CRONOLOGIA setRespCampoAsig()       Sets the current record's "resp_campo_asig" value
 * @method CRONOLOGIA setKvaAsig()             Sets the current record's "kva_asig" value
 * @method CRONOLOGIA setFechaLleg()           Sets the current record's "fecha_lleg" value
 * @method CRONOLOGIA setRespMesaLleg()        Sets the current record's "resp_mesa_lleg" value
 * @method CRONOLOGIA setRespCampoLleg()       Sets the current record's "resp_campo_lleg" value
 * @method CRONOLOGIA setFechaLocGrue()        Sets the current record's "fecha_loc_grue" value
 * @method CRONOLOGIA setRespMesaLocGrue()     Sets the current record's "resp_mesa_loc_grue" value
 * @method CRONOLOGIA setRespCampoLocGrue()    Sets the current record's "resp_campo_loc_grue" value
 * @method CRONOLOGIA setKvaLocGrue()          Sets the current record's "kva_loc_grue" value
 * @method CRONOLOGIA setFechaLocFina()        Sets the current record's "fecha_loc_fina" value
 * @method CRONOLOGIA setRespMesaLocFina()     Sets the current record's "resp_mesa_loc_fina" value
 * @method CRONOLOGIA setRespCampoLocFina()    Sets the current record's "resp_campo_loc_fina" value
 * @method CRONOLOGIA setKvaLocFina()          Sets the current record's "kva_loc_fina" value
 * @method CRONOLOGIA setFechaReparacion()     Sets the current record's "fecha_reparacion" value
 * @method CRONOLOGIA setRespMesaRep()         Sets the current record's "resp_mesa_rep" value
 * @method CRONOLOGIA setRespCampoRep()        Sets the current record's "resp_campo_rep" value
 * @method CRONOLOGIA setKvaReparacion()       Sets the current record's "kva_reparacion" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCRONOLOGIA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CRONOLOGIA');
        $this->hasColumn('num_f328', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 7,
             ));
        $this->hasColumn('fecha_asig', 'timestamp', 7, array(
             'notnull' => true,
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('resp_mesa_asig', 'string', 5, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('resp_campo_asig', 'string', 11, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 11,
             ));
        $this->hasColumn('kva_asig', 'integer', 7, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('fecha_lleg', 'timestamp', 7, array(
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('resp_mesa_lleg', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('resp_campo_lleg', 'string', 11, array(
             'type' => 'string',
             'length' => 11,
             ));
        $this->hasColumn('fecha_loc_grue', 'timestamp', 7, array(
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('resp_mesa_loc_grue', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('resp_campo_loc_grue', 'string', 11, array(
             'type' => 'string',
             'length' => 11,
             ));
        $this->hasColumn('kva_loc_grue', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('fecha_loc_fina', 'timestamp', 7, array(
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('resp_mesa_loc_fina', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('resp_campo_loc_fina', 'string', 11, array(
             'type' => 'string',
             'length' => 11,
             ));
        $this->hasColumn('kva_loc_fina', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('fecha_reparacion', 'timestamp', 7, array(
             'notnull' => true,
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('resp_mesa_rep', 'string', 5, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('resp_campo_rep', 'string', 11, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 11,
             ));
        $this->hasColumn('kva_reparacion', 'integer', 7, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}