<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_FOTO', 'schema_saf');

/**
 * BaseSAF_FOTO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $titulo
 * @property string $dir
 * @property integer $id_evento
 * @property string $sub_titulo
 * @property SAF_EVENTO $SAF_EVENTO
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getTitulo()     Returns the current record's "titulo" value
 * @method string     getDir()        Returns the current record's "dir" value
 * @method integer    getIdEvento()   Returns the current record's "id_evento" value
 * @method string     getSubTitulo()  Returns the current record's "sub_titulo" value
 * @method SAF_EVENTO getSAFEVENTO()  Returns the current record's "SAF_EVENTO" value
 * @method SAF_FOTO   setId()         Sets the current record's "id" value
 * @method SAF_FOTO   setTitulo()     Sets the current record's "titulo" value
 * @method SAF_FOTO   setDir()        Sets the current record's "dir" value
 * @method SAF_FOTO   setIdEvento()   Sets the current record's "id_evento" value
 * @method SAF_FOTO   setSubTitulo()  Sets the current record's "sub_titulo" value
 * @method SAF_FOTO   setSAFEVENTO()  Sets the current record's "SAF_EVENTO" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_FOTO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_FOTO');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'SAF_FOTO',
             ));
        $this->hasColumn('titulo', 'string', 100, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('dir', 'string', 100, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('id_evento', 'integer', null, array(
             'notnull' => false,
             'type' => 'integer',
             ));
        $this->hasColumn('sub_titulo', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_EVENTO', array(
             'local' => 'id_evento',
             'foreign' => 'id'));
    }
}