<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_TAREA_REALIZADA_COMP', 'schema_saf');

/**
 * BaseSAF_TAREA_REALIZADA_COMP
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_comp_ue
 * @property string $descripcion
 * @property SAF_COMP_UE $SAF_COMP_UE
 * 
 * @method integer                  getId()          Returns the current record's "id" value
 * @method integer                  getIdCompUe()    Returns the current record's "id_comp_ue" value
 * @method string                   getDescripcion() Returns the current record's "descripcion" value
 * @method SAF_COMP_UE              getSAFCOMPUE()   Returns the current record's "SAF_COMP_UE" value
 * @method SAF_TAREA_REALIZADA_COMP setId()          Sets the current record's "id" value
 * @method SAF_TAREA_REALIZADA_COMP setIdCompUe()    Sets the current record's "id_comp_ue" value
 * @method SAF_TAREA_REALIZADA_COMP setDescripcion() Sets the current record's "descripcion" value
 * @method SAF_TAREA_REALIZADA_COMP setSAFCOMPUE()   Sets the current record's "SAF_COMP_UE" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_TAREA_REALIZADA_COMP extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_TAREA_REALIZADA_COMP');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'SAF_TAREA_REALIZADA_COMP',
             ));
        $this->hasColumn('id_comp_ue', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('descripcion', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_COMP_UE', array(
             'local' => 'id_comp_ue',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}