<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CAUSA', 'schema_siod');

/**
 * BaseCAUSA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_causa
 * @property string $desc_causa
 * 
 * @method integer getCodCausa()   Returns the current record's "cod_causa" value
 * @method string  getDescCausa()  Returns the current record's "desc_causa" value
 * @method CAUSA   setCodCausa()   Sets the current record's "cod_causa" value
 * @method CAUSA   setDescCausa()  Sets the current record's "desc_causa" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCAUSA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CAUSA');
        $this->hasColumn('cod_causa', 'integer', 3, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 3,
             ));
        $this->hasColumn('desc_causa', 'string', 50, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}