<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CRONOLOGIA', 'schema_siod');

/**
 * BaseCRONOLOGIA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $num_f328
 * @property timestamp $fecha_reparacion
 * @property string $resp_mesa_rep
 * 
 * @method integer    getNumF328()          Returns the current record's "num_f328" value
 * @method timestamp  getFechaReparacion()  Returns the current record's "fecha_reparacion" value
 * @method string     getRespMesaRep()      Returns the current record's "resp_mesa_rep" value
 * @method CRONOLOGIA setNumF328()          Sets the current record's "num_f328" value
 * @method CRONOLOGIA setFechaReparacion()  Sets the current record's "fecha_reparacion" value
 * @method CRONOLOGIA setRespMesaRep()      Sets the current record's "resp_mesa_rep" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCRONOLOGIA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CRONOLOGIA');
        $this->hasColumn('num_f328', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 7,
             ));
        $this->hasColumn('fecha_reparacion', 'timestamp', 7, array(
             'notnull' => true,
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('resp_mesa_rep', 'string', 5, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}