<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HIST_PROPOSICIONES', 'schema_simip');

/**
 * BaseHIST_PROPOSICIONES
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_proposicion
 * @property integer $oper_cod_operador_resp
 * @property integer $oper_cod_operador_asig
 * 
 * @method integer            getCodProposicion()         Returns the current record's "cod_proposicion" value
 * @method integer            getOperCodOperadorResp()    Returns the current record's "oper_cod_operador_resp" value
 * @method integer            getOperCodOperadorAsig()    Returns the current record's "oper_cod_operador_asig" value
 * @method HIST_PROPOSICIONES setCodProposicion()         Sets the current record's "cod_proposicion" value
 * @method HIST_PROPOSICIONES setOperCodOperadorResp()    Sets the current record's "oper_cod_operador_resp" value
 * @method HIST_PROPOSICIONES setOperCodOperadorAsig()    Sets the current record's "oper_cod_operador_asig" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHIST_PROPOSICIONES extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('HIST_PROPOSICIONES');
        $this->hasColumn('cod_proposicion', 'integer', 6, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('oper_cod_operador_resp', 'integer', 8, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('oper_cod_operador_asig', 'integer', 8, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}