<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OPERADORES', 'schema_simip');

/**
 * BaseOPERADORES
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_operador
 * @property string $desc_operador
 * 
 * @method integer    getCodOperador()   Returns the current record's "cod_operador" value
 * @method string     getDescOperador()  Returns the current record's "desc_operador" value
 * @method OPERADORES setCodOperador()   Sets the current record's "cod_operador" value
 * @method OPERADORES setDescOperador()  Sets the current record's "desc_operador" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOPERADORES extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('OPERADORES');
        $this->hasColumn('cod_operador', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('desc_operador', 'string', 30, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}