<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AVERIA', 'schema_siod');

/**
 * BaseAVERIA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $num_averia
 * @property string $descripcion
 * 
 * @method integer getNumAveria()   Returns the current record's "num_averia" value
 * @method string  getDescripcion() Returns the current record's "descripcion" value
 * @method AVERIA  setNumAveria()   Sets the current record's "num_averia" value
 * @method AVERIA  setDescripcion() Sets the current record's "descripcion" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAVERIA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('AVERIA');
        $this->hasColumn('num_averia', 'integer', 9, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 9,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}