<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_MINUTA', 'schema_saf');

/**
 * BaseSAF_MINUTA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_min
 * @property integer $id_convocatoria
 * @property string $dir_pdf
 * @property SAF_CONVOCATORIA_CAF $SAF_CONVOCATORIA_CAF
 * 
 * @method integer              getCodMin()               Returns the current record's "cod_min" value
 * @method integer              getIdConvocatoria()       Returns the current record's "id_convocatoria" value
 * @method string               getDirPdf()               Returns the current record's "dir_pdf" value
 * @method SAF_CONVOCATORIA_CAF getSAFCONVOCATORIACAF()   Returns the current record's "SAF_CONVOCATORIA_CAF" value
 * @method SAF_MINUTA           setCodMin()               Sets the current record's "cod_min" value
 * @method SAF_MINUTA           setIdConvocatoria()       Sets the current record's "id_convocatoria" value
 * @method SAF_MINUTA           setDirPdf()               Sets the current record's "dir_pdf" value
 * @method SAF_MINUTA           setSAFCONVOCATORIACAF()   Sets the current record's "SAF_CONVOCATORIA_CAF" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_MINUTA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_MINUTA');
        $this->hasColumn('cod_min', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'SAF_MINUTA',
             ));
        $this->hasColumn('id_convocatoria', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             'unique' => true,
             ));
        $this->hasColumn('dir_pdf', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_CONVOCATORIA_CAF', array(
             'local' => 'id_convocatoria',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}