<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UNIDAD_SOPORTES', 'schema_siod');

/**
 * BaseUNIDAD_SOPORTES
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_unidad
 * @property string $descripcion
 * @property string $ind_atencion_soporte
 * 
 * @method integer         getCodUnidad()            Returns the current record's "cod_unidad" value
 * @method string          getDescripcion()          Returns the current record's "descripcion" value
 * @method string          getIndAtencionSoporte()   Returns the current record's "ind_atencion_soporte" value
 * @method UNIDAD_SOPORTES setCodUnidad()            Sets the current record's "cod_unidad" value
 * @method UNIDAD_SOPORTES setDescripcion()          Sets the current record's "descripcion" value
 * @method UNIDAD_SOPORTES setIndAtencionSoporte()   Sets the current record's "ind_atencion_soporte" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUNIDAD_SOPORTES extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('UNIDAD_SOPORTES');
        $this->hasColumn('cod_unidad', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('descripcion', 'string', 40, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('ind_atencion_soporte', 'string', 1, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}