<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_ASISTENCIA', 'schema_saf');

/**
 * BaseSAF_ASISTENCIA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_convocatoria
 * @property integer $id_personal
 * @property SAF_CONVOCATORIA_CAF $SAF_CONVOCATORIA_CAF
 * @property SAF_PERSONAL $SAF_PERSONAL
 * 
 * @method integer              getIdConvocatoria()       Returns the current record's "id_convocatoria" value
 * @method integer              getIdPersonal()           Returns the current record's "id_personal" value
 * @method SAF_CONVOCATORIA_CAF getSAFCONVOCATORIACAF()   Returns the current record's "SAF_CONVOCATORIA_CAF" value
 * @method SAF_PERSONAL         getSAFPERSONAL()          Returns the current record's "SAF_PERSONAL" value
 * @method SAF_ASISTENCIA       setIdConvocatoria()       Sets the current record's "id_convocatoria" value
 * @method SAF_ASISTENCIA       setIdPersonal()           Sets the current record's "id_personal" value
 * @method SAF_ASISTENCIA       setSAFCONVOCATORIACAF()   Sets the current record's "SAF_CONVOCATORIA_CAF" value
 * @method SAF_ASISTENCIA       setSAFPERSONAL()          Sets the current record's "SAF_PERSONAL" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_ASISTENCIA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_ASISTENCIA');
        $this->hasColumn('id_convocatoria', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_personal', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_CONVOCATORIA_CAF', array(
             'local' => 'id_convocatoria',
             'foreign' => 'id'));

        $this->hasOne('SAF_PERSONAL', array(
             'local' => 'id_personal',
             'foreign' => 'ci'));
    }
}