<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CIRCUITOS', 'schema_simip');

/**
 * BaseCIRCUITOS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_cto
 * @property integer $bar_cod_barra
 * @property string $desc_cto
 * 
 * @method integer   getCodCto()        Returns the current record's "cod_cto" value
 * @method integer   getBarCodBarra()   Returns the current record's "bar_cod_barra" value
 * @method string    getDescCto()       Returns the current record's "desc_cto" value
 * @method CIRCUITOS setCodCto()        Sets the current record's "cod_cto" value
 * @method CIRCUITOS setBarCodBarra()   Sets the current record's "bar_cod_barra" value
 * @method CIRCUITOS setDescCto()       Sets the current record's "desc_cto" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCIRCUITOS extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CIRCUITOS');
        $this->hasColumn('cod_cto', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('bar_cod_barra', 'integer', 4, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('desc_cto', 'string', 30, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}