<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_R1000_MVAMIN', 'schema_saf');

/**
 * BaseSAF_R1000_MVAMIN
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_evento
 * @property string $razon
 * @property integer $valor
 * @property SAF_EVENTO $SAF_EVENTO
 * 
 * @method integer          getId()         Returns the current record's "id" value
 * @method integer          getIdEvento()   Returns the current record's "id_evento" value
 * @method string           getRazon()      Returns the current record's "razon" value
 * @method integer          getValor()      Returns the current record's "valor" value
 * @method SAF_EVENTO       getSAFEVENTO()  Returns the current record's "SAF_EVENTO" value
 * @method SAF_R1000_MVAMIN setId()         Sets the current record's "id" value
 * @method SAF_R1000_MVAMIN setIdEvento()   Sets the current record's "id_evento" value
 * @method SAF_R1000_MVAMIN setRazon()      Sets the current record's "razon" value
 * @method SAF_R1000_MVAMIN setValor()      Sets the current record's "valor" value
 * @method SAF_R1000_MVAMIN setSAFEVENTO()  Sets the current record's "SAF_EVENTO" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_R1000_MVAMIN extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_R1000_MVAMIN');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'SAF_R1000_MVAMIN',
             ));
        $this->hasColumn('id_evento', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('razon', 'string', 50, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('valor', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_EVENTO', array(
             'local' => 'id_evento',
             'foreign' => 'id'));
    }
}