<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_EVENTO', 'schema_saf');

/**
 * BaseSAF_EVENTO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property string $clasificado_en
 * @property integer $id_agenda
 * @property integer $id_convocatoria
 * @property integer $c_eveno_t
 * @property integer $c_evento_d
 * @property string $status
 * @property SAF_AGENDA_CONVOCATORIA $SAF_AGENDA_CONVOCATORIA
 * @property SAF_CONVOCATORIA_CAF $SAF_CONVOCATORIA_CAF
 * @property Doctrine_Collection $SAF_FOTO
 * @property Doctrine_Collection $Razones_1000MvaMin
 * @property Doctrine_Collection $SAF_VARIO
 * 
 * @method integer                 getId()                      Returns the current record's "id" value
 * @method string                  getDescripcion()             Returns the current record's "descripcion" value
 * @method string                  getClasificadoEn()           Returns the current record's "clasificado_en" value
 * @method integer                 getIdAgenda()                Returns the current record's "id_agenda" value
 * @method integer                 getIdConvocatoria()          Returns the current record's "id_convocatoria" value
 * @method integer                 getCEvenoT()                 Returns the current record's "c_eveno_t" value
 * @method integer                 getCEventoD()                Returns the current record's "c_evento_d" value
 * @method string                  getStatus()                  Returns the current record's "status" value
 * @method SAF_AGENDA_CONVOCATORIA getSAFAGENDACONVOCATORIA()   Returns the current record's "SAF_AGENDA_CONVOCATORIA" value
 * @method SAF_CONVOCATORIA_CAF    getSAFCONVOCATORIACAF()      Returns the current record's "SAF_CONVOCATORIA_CAF" value
 * @method Doctrine_Collection     getSAFFOTO()                 Returns the current record's "SAF_FOTO" collection
 * @method Doctrine_Collection     getRazones1000MvaMin()       Returns the current record's "Razones_1000MvaMin" collection
 * @method Doctrine_Collection     getSAFVARIO()                Returns the current record's "SAF_VARIO" collection
 * @method SAF_EVENTO              setId()                      Sets the current record's "id" value
 * @method SAF_EVENTO              setDescripcion()             Sets the current record's "descripcion" value
 * @method SAF_EVENTO              setClasificadoEn()           Sets the current record's "clasificado_en" value
 * @method SAF_EVENTO              setIdAgenda()                Sets the current record's "id_agenda" value
 * @method SAF_EVENTO              setIdConvocatoria()          Sets the current record's "id_convocatoria" value
 * @method SAF_EVENTO              setCEvenoT()                 Sets the current record's "c_eveno_t" value
 * @method SAF_EVENTO              setCEventoD()                Sets the current record's "c_evento_d" value
 * @method SAF_EVENTO              setStatus()                  Sets the current record's "status" value
 * @method SAF_EVENTO              setSAFAGENDACONVOCATORIA()   Sets the current record's "SAF_AGENDA_CONVOCATORIA" value
 * @method SAF_EVENTO              setSAFCONVOCATORIACAF()      Sets the current record's "SAF_CONVOCATORIA_CAF" value
 * @method SAF_EVENTO              setSAFFOTO()                 Sets the current record's "SAF_FOTO" collection
 * @method SAF_EVENTO              setRazones1000MvaMin()       Sets the current record's "Razones_1000MvaMin" collection
 * @method SAF_EVENTO              setSAFVARIO()                Sets the current record's "SAF_VARIO" collection
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_EVENTO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_EVENTO');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'SAF_EVENTO',
             ));
        $this->hasColumn('descripcion', 'string', 500, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('clasificado_en', 'string', 50, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('id_agenda', 'integer', null, array(
             'notnull' => false,
             'type' => 'integer',
             ));
        $this->hasColumn('id_convocatoria', 'integer', null, array(
             'notnull' => false,
             'type' => 'integer',
             ));
        $this->hasColumn('c_eveno_t', 'integer', null, array(
             'notnull' => false,
             'type' => 'integer',
             ));
        $this->hasColumn('c_evento_d', 'integer', null, array(
             'notnull' => false,
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_AGENDA_CONVOCATORIA', array(
             'local' => 'id_agenda',
             'foreign' => 'id'));

        $this->hasOne('SAF_CONVOCATORIA_CAF', array(
             'local' => 'id_convocatoria',
             'foreign' => 'id'));

        $this->hasMany('SAF_FOTO', array(
             'local' => 'id',
             'foreign' => 'id_evento'));

        $this->hasMany('SAF_R1000_MVAMIN as Razones_1000MvaMin', array(
             'local' => 'id',
             'foreign' => 'id_evento'));

        $this->hasMany('SAF_VARIO', array(
             'local' => 'id',
             'foreign' => 'id_evento'));
    }
}