<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('INTERRUPCIONES', 'schema_siod');

/**
 * BaseINTERRUPCIONES
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $num_f328
 * @property integer $nivel_sistema
 * @property integer $cod_sistema
 * @property timestamp $fecha_hora_ini
 * @property integer $duracion_max
 * @property integer $kva_interrump
 * @property decimal $mvamin
 * @property string $cod_cuadricula
 * @property integer $cod_ubicacion
 * @property integer $num_oper_int
 * @property integer $tipo_alarma
 * @property integer $cod_oper_alarma
 * @property integer $cod_oper_protec
 * @property integer $voltaje
 * @property integer $cod_material
 * @property integer $cod_causa
 * @property string $resp_campo
 * @property string $resp_mesa_inic
 * @property string $resp_mesa_fin
 * @property string $cod_unidad_oper
 * @property string $mod_red
 * @property string $ubicacion_tecnica
 * @property timestamp $fecha_transf
 * @property integer $tipo_red
 * @property integer $distrito
 * @property integer $ind_tipo_equipo
 * @property integer $cod_equipo
 * @property integer $ind_tramo
 * @property integer $cod_tramo
 * @property integer $num_proposicion
 * @property string $trabajo_realizado
 * @property string $direccion
 * @property integer $tamano
 * @property integer $unidades
 * @property decimal $costo
 * @property integer $horas_hombre
 * @property string $cod_marca
 * @property integer $climatologia
 * @property string $num_reclamo
 * @property string $n_mem_cco
 * @property integer $num_roe
 * @property integer $num_averia
 * @property integer $cant_personas
 * @property integer $tipo_falla
 * @property integer $cant_fases_afect
 * 
 * @method integer        getNumF328()           Returns the current record's "num_f328" value
 * @method integer        getNivelSistema()      Returns the current record's "nivel_sistema" value
 * @method integer        getCodSistema()        Returns the current record's "cod_sistema" value
 * @method timestamp      getFechaHoraIni()      Returns the current record's "fecha_hora_ini" value
 * @method integer        getDuracionMax()       Returns the current record's "duracion_max" value
 * @method integer        getKvaInterrump()      Returns the current record's "kva_interrump" value
 * @method decimal        getMvamin()            Returns the current record's "mvamin" value
 * @method string         getCodCuadricula()     Returns the current record's "cod_cuadricula" value
 * @method integer        getCodUbicacion()      Returns the current record's "cod_ubicacion" value
 * @method integer        getNumOperInt()        Returns the current record's "num_oper_int" value
 * @method integer        getTipoAlarma()        Returns the current record's "tipo_alarma" value
 * @method integer        getCodOperAlarma()     Returns the current record's "cod_oper_alarma" value
 * @method integer        getCodOperProtec()     Returns the current record's "cod_oper_protec" value
 * @method integer        getVoltaje()           Returns the current record's "voltaje" value
 * @method integer        getCodMaterial()       Returns the current record's "cod_material" value
 * @method integer        getCodCausa()          Returns the current record's "cod_causa" value
 * @method string         getRespCampo()         Returns the current record's "resp_campo" value
 * @method string         getRespMesaInic()      Returns the current record's "resp_mesa_inic" value
 * @method string         getRespMesaFin()       Returns the current record's "resp_mesa_fin" value
 * @method string         getCodUnidadOper()     Returns the current record's "cod_unidad_oper" value
 * @method string         getModRed()            Returns the current record's "mod_red" value
 * @method string         getUbicacionTecnica()  Returns the current record's "ubicacion_tecnica" value
 * @method timestamp      getFechaTransf()       Returns the current record's "fecha_transf" value
 * @method integer        getTipoRed()           Returns the current record's "tipo_red" value
 * @method integer        getDistrito()          Returns the current record's "distrito" value
 * @method integer        getIndTipoEquipo()     Returns the current record's "ind_tipo_equipo" value
 * @method integer        getCodEquipo()         Returns the current record's "cod_equipo" value
 * @method integer        getIndTramo()          Returns the current record's "ind_tramo" value
 * @method integer        getCodTramo()          Returns the current record's "cod_tramo" value
 * @method integer        getNumProposicion()    Returns the current record's "num_proposicion" value
 * @method string         getTrabajoRealizado()  Returns the current record's "trabajo_realizado" value
 * @method string         getDireccion()         Returns the current record's "direccion" value
 * @method integer        getTamano()            Returns the current record's "tamano" value
 * @method integer        getUnidades()          Returns the current record's "unidades" value
 * @method decimal        getCosto()             Returns the current record's "costo" value
 * @method integer        getHorasHombre()       Returns the current record's "horas_hombre" value
 * @method string         getCodMarca()          Returns the current record's "cod_marca" value
 * @method integer        getClimatologia()      Returns the current record's "climatologia" value
 * @method string         getNumReclamo()        Returns the current record's "num_reclamo" value
 * @method string         getNMemCco()           Returns the current record's "n_mem_cco" value
 * @method integer        getNumRoe()            Returns the current record's "num_roe" value
 * @method integer        getNumAveria()         Returns the current record's "num_averia" value
 * @method integer        getCantPersonas()      Returns the current record's "cant_personas" value
 * @method integer        getTipoFalla()         Returns the current record's "tipo_falla" value
 * @method integer        getCantFasesAfect()    Returns the current record's "cant_fases_afect" value
 * @method INTERRUPCIONES setNumF328()           Sets the current record's "num_f328" value
 * @method INTERRUPCIONES setNivelSistema()      Sets the current record's "nivel_sistema" value
 * @method INTERRUPCIONES setCodSistema()        Sets the current record's "cod_sistema" value
 * @method INTERRUPCIONES setFechaHoraIni()      Sets the current record's "fecha_hora_ini" value
 * @method INTERRUPCIONES setDuracionMax()       Sets the current record's "duracion_max" value
 * @method INTERRUPCIONES setKvaInterrump()      Sets the current record's "kva_interrump" value
 * @method INTERRUPCIONES setMvamin()            Sets the current record's "mvamin" value
 * @method INTERRUPCIONES setCodCuadricula()     Sets the current record's "cod_cuadricula" value
 * @method INTERRUPCIONES setCodUbicacion()      Sets the current record's "cod_ubicacion" value
 * @method INTERRUPCIONES setNumOperInt()        Sets the current record's "num_oper_int" value
 * @method INTERRUPCIONES setTipoAlarma()        Sets the current record's "tipo_alarma" value
 * @method INTERRUPCIONES setCodOperAlarma()     Sets the current record's "cod_oper_alarma" value
 * @method INTERRUPCIONES setCodOperProtec()     Sets the current record's "cod_oper_protec" value
 * @method INTERRUPCIONES setVoltaje()           Sets the current record's "voltaje" value
 * @method INTERRUPCIONES setCodMaterial()       Sets the current record's "cod_material" value
 * @method INTERRUPCIONES setCodCausa()          Sets the current record's "cod_causa" value
 * @method INTERRUPCIONES setRespCampo()         Sets the current record's "resp_campo" value
 * @method INTERRUPCIONES setRespMesaInic()      Sets the current record's "resp_mesa_inic" value
 * @method INTERRUPCIONES setRespMesaFin()       Sets the current record's "resp_mesa_fin" value
 * @method INTERRUPCIONES setCodUnidadOper()     Sets the current record's "cod_unidad_oper" value
 * @method INTERRUPCIONES setModRed()            Sets the current record's "mod_red" value
 * @method INTERRUPCIONES setUbicacionTecnica()  Sets the current record's "ubicacion_tecnica" value
 * @method INTERRUPCIONES setFechaTransf()       Sets the current record's "fecha_transf" value
 * @method INTERRUPCIONES setTipoRed()           Sets the current record's "tipo_red" value
 * @method INTERRUPCIONES setDistrito()          Sets the current record's "distrito" value
 * @method INTERRUPCIONES setIndTipoEquipo()     Sets the current record's "ind_tipo_equipo" value
 * @method INTERRUPCIONES setCodEquipo()         Sets the current record's "cod_equipo" value
 * @method INTERRUPCIONES setIndTramo()          Sets the current record's "ind_tramo" value
 * @method INTERRUPCIONES setCodTramo()          Sets the current record's "cod_tramo" value
 * @method INTERRUPCIONES setNumProposicion()    Sets the current record's "num_proposicion" value
 * @method INTERRUPCIONES setTrabajoRealizado()  Sets the current record's "trabajo_realizado" value
 * @method INTERRUPCIONES setDireccion()         Sets the current record's "direccion" value
 * @method INTERRUPCIONES setTamano()            Sets the current record's "tamano" value
 * @method INTERRUPCIONES setUnidades()          Sets the current record's "unidades" value
 * @method INTERRUPCIONES setCosto()             Sets the current record's "costo" value
 * @method INTERRUPCIONES setHorasHombre()       Sets the current record's "horas_hombre" value
 * @method INTERRUPCIONES setCodMarca()          Sets the current record's "cod_marca" value
 * @method INTERRUPCIONES setClimatologia()      Sets the current record's "climatologia" value
 * @method INTERRUPCIONES setNumReclamo()        Sets the current record's "num_reclamo" value
 * @method INTERRUPCIONES setNMemCco()           Sets the current record's "n_mem_cco" value
 * @method INTERRUPCIONES setNumRoe()            Sets the current record's "num_roe" value
 * @method INTERRUPCIONES setNumAveria()         Sets the current record's "num_averia" value
 * @method INTERRUPCIONES setCantPersonas()      Sets the current record's "cant_personas" value
 * @method INTERRUPCIONES setTipoFalla()         Sets the current record's "tipo_falla" value
 * @method INTERRUPCIONES setCantFasesAfect()    Sets the current record's "cant_fases_afect" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseINTERRUPCIONES extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('INTERRUPCIONES');
        $this->hasColumn('num_f328', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 7,
             ));
        $this->hasColumn('nivel_sistema', 'integer', 1, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cod_sistema', 'integer', 5, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('fecha_hora_ini', 'timestamp', 7, array(
             'notnull' => true,
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('duracion_max', 'integer', 5, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('kva_interrump', 'integer', 7, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('mvamin', 'decimal', 7, array(
             'notnull' => true,
             'type' => 'decimal',
             'length' => 7,
             ));
        $this->hasColumn('cod_cuadricula', 'string', 5, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('cod_ubicacion', 'integer', 5, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('num_oper_int', 'integer', 2, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('tipo_alarma', 'integer', 1, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cod_oper_alarma', 'integer', 1, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cod_oper_protec', 'integer', 1, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('voltaje', 'integer', 2, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('cod_material', 'integer', 3, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('cod_causa', 'integer', 3, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('resp_campo', 'string', 11, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 11,
             ));
        $this->hasColumn('resp_mesa_inic', 'string', 5, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('resp_mesa_fin', 'string', 5, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('cod_unidad_oper', 'string', 8, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('mod_red', 'string', 1, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('ubicacion_tecnica', 'string', 30, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('fecha_transf', 'timestamp', 7, array(
             'notnull' => true,
             'type' => 'timestamp',
             'length' => 7,
             ));
        $this->hasColumn('tipo_red', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('distrito', 'integer', 2, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('ind_tipo_equipo', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cod_equipo', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('ind_tramo', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('cod_tramo', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('num_proposicion', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('trabajo_realizado', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('direccion', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('tamano', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('unidades', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('costo', 'decimal', 12, array(
             'type' => 'decimal',
             'length' => 12,
             ));
        $this->hasColumn('horas_hombre', 'integer', 6, array(
             'type' => 'integer',
             'length' => 6,
             ));
        $this->hasColumn('cod_marca', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('climatologia', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('num_reclamo', 'string', 12, array(
             'type' => 'string',
             'length' => 12,
             ));
        $this->hasColumn('n_mem_cco', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('num_roe', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('num_averia', 'integer', 9, array(
             'type' => 'integer',
             'length' => 9,
             ));
        $this->hasColumn('cant_personas', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('tipo_falla', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('cant_fases_afect', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}