<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_PERSONAL', 'schema_saf');

/**
 * BaseSAF_PERSONAL
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ci
 * @property integer $id_ue
 * @property string $nombre
 * @property string $apellido
 * @property string $correo
 * @property SAF_UNIDAD_EQUIPO $SAF_UNIDAD_EQUIPO
 * @property Doctrine_Collection $SAF_ASISTENCIA
 * 
 * @method integer             getCi()                Returns the current record's "ci" value
 * @method integer             getIdUe()              Returns the current record's "id_ue" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method string              getApellido()          Returns the current record's "apellido" value
 * @method string              getCorreo()            Returns the current record's "correo" value
 * @method SAF_UNIDAD_EQUIPO   getSAFUNIDADEQUIPO()   Returns the current record's "SAF_UNIDAD_EQUIPO" value
 * @method Doctrine_Collection getSAFASISTENCIA()     Returns the current record's "SAF_ASISTENCIA" collection
 * @method SAF_PERSONAL        setCi()                Sets the current record's "ci" value
 * @method SAF_PERSONAL        setIdUe()              Sets the current record's "id_ue" value
 * @method SAF_PERSONAL        setNombre()            Sets the current record's "nombre" value
 * @method SAF_PERSONAL        setApellido()          Sets the current record's "apellido" value
 * @method SAF_PERSONAL        setCorreo()            Sets the current record's "correo" value
 * @method SAF_PERSONAL        setSAFUNIDADEQUIPO()   Sets the current record's "SAF_UNIDAD_EQUIPO" value
 * @method SAF_PERSONAL        setSAFASISTENCIA()     Sets the current record's "SAF_ASISTENCIA" collection
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_PERSONAL extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_PERSONAL');
        $this->hasColumn('ci', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_ue', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('apellido', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('correo', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_UNIDAD_EQUIPO', array(
             'local' => 'id_ue',
             'foreign' => 'id'));

        $this->hasMany('SAF_ASISTENCIA', array(
             'local' => 'ci',
             'foreign' => 'id_personal'));
    }
}