<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_F_CONVOCATORIA_CAF', 'schema_saf');

/**
 * BaseSAF_F_CONVOCATORIA_CAF
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $fecha
 * @property integer $id_convocatoria
 * @property string $status
 * @property string $motivo_suspencion
 * @property SAF_CONVOCATORIA_CAF $SAF_CONVOCATORIA_CAF
 * 
 * @method timestamp              getFecha()                Returns the current record's "fecha" value
 * @method integer                getIdConvocatoria()       Returns the current record's "id_convocatoria" value
 * @method string                 getStatus()               Returns the current record's "status" value
 * @method string                 getMotivoSuspencion()     Returns the current record's "motivo_suspencion" value
 * @method SAF_CONVOCATORIA_CAF   getSAFCONVOCATORIACAF()   Returns the current record's "SAF_CONVOCATORIA_CAF" value
 * @method SAF_F_CONVOCATORIA_CAF setFecha()                Sets the current record's "fecha" value
 * @method SAF_F_CONVOCATORIA_CAF setIdConvocatoria()       Sets the current record's "id_convocatoria" value
 * @method SAF_F_CONVOCATORIA_CAF setStatus()               Sets the current record's "status" value
 * @method SAF_F_CONVOCATORIA_CAF setMotivoSuspencion()     Sets the current record's "motivo_suspencion" value
 * @method SAF_F_CONVOCATORIA_CAF setSAFCONVOCATORIACAF()   Sets the current record's "SAF_CONVOCATORIA_CAF" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_F_CONVOCATORIA_CAF extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_F_CONVOCATORIA_CAF');
        $this->hasColumn('fecha', 'timestamp', 7, array(
             'type' => 'timestamp',
             'primary' => true,
             'length' => 7,
             ));
        $this->hasColumn('id_convocatoria', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'string', 50, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('motivo_suspencion', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_CONVOCATORIA_CAF', array(
             'local' => 'id_convocatoria',
             'foreign' => 'id'));
    }
}