<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SAF_COMP_UE', 'schema_saf');

/**
 * BaseSAF_COMP_UE
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_compromiso
 * @property integer $id_ue
 * @property string $status
 * @property string $acciones
 * @property SAF_VARIO $SAF_VARIO
 * @property SAF_UNIDAD_EQUIPO $SAF_UNIDAD_EQUIPO
 * 
 * @method integer           getId()                Returns the current record's "id" value
 * @method integer           getIdCompromiso()      Returns the current record's "id_compromiso" value
 * @method integer           getIdUe()              Returns the current record's "id_ue" value
 * @method string            getStatus()            Returns the current record's "status" value
 * @method string            getAcciones()          Returns the current record's "acciones" value
 * @method SAF_VARIO         getSAFVARIO()          Returns the current record's "SAF_VARIO" value
 * @method SAF_UNIDAD_EQUIPO getSAFUNIDADEQUIPO()   Returns the current record's "SAF_UNIDAD_EQUIPO" value
 * @method SAF_COMP_UE       setId()                Sets the current record's "id" value
 * @method SAF_COMP_UE       setIdCompromiso()      Sets the current record's "id_compromiso" value
 * @method SAF_COMP_UE       setIdUe()              Sets the current record's "id_ue" value
 * @method SAF_COMP_UE       setStatus()            Sets the current record's "status" value
 * @method SAF_COMP_UE       setAcciones()          Sets the current record's "acciones" value
 * @method SAF_COMP_UE       setSAFVARIO()          Sets the current record's "SAF_VARIO" value
 * @method SAF_COMP_UE       setSAFUNIDADEQUIPO()   Sets the current record's "SAF_UNIDAD_EQUIPO" value
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSAF_COMP_UE extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SAF_COMP_UE');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'sequence' => 'SAF_COMP_UE',
             ));
        $this->hasColumn('id_compromiso', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('id_ue', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'string', 50, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('acciones', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SAF_VARIO', array(
             'local' => 'id_compromiso',
             'foreign' => 'id'));

        $this->hasOne('SAF_UNIDAD_EQUIPO', array(
             'local' => 'id_ue',
             'foreign' => 'id'));
    }
}