<?php

/**
 * AVERIATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AVERIATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AVERIATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AVERIA');
    }
}