<?php

/**
 * CAUSATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CAUSATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CAUSATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CAUSA');
    }
}