<?php

/**
 * CRONOLOGIA_CUADRILLA_INTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CRONOLOGIA_CUADRILLA_INTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CRONOLOGIA_CUADRILLA_INTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CRONOLOGIA_CUADRILLA_INT');
    }
}