<?php

/**
 * CRONOLOGIA_CUADRILLA_INTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CRONOLOGIA_CUADRILLA_INTTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object CRONOLOGIA_CUADRILLA_INTTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('CRONOLOGIA_CUADRILLA_INT');
  }
  
  /**
   * Método que retorna un objeto del modelo CRONOLOGIA_CUADRILLA_INT del schema
   * SIOD, si el numero f328 es igual al de la interrupcion.
   * 
   * @param Integer $num_f328
   * @return CRONOLOGIA_CUADRILLA_INTEGER
   */
  public function getCuadrilla($num_f328)
  {
    $query = $this->createQuery()
            ->where('num_f328 = ?', $num_f328);
    
    return $query->fetchOne();
  }
  
}