<?php

/**
 * CRONOLOGIATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CRONOLOGIATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CRONOLOGIATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CRONOLOGIA');
    }
}