<?php

/**
 * MATERIALTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MATERIALTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MATERIALTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MATERIAL');
    }
}