<?php

/**
 * OPERADORESTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OPERADORESTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OPERADORESTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OPERADORES');
    }
}