<?php

/**
 * SAF_R1000_MVAMIN
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SAF_R1000_MVAMIN extends BaseSAF_R1000_MVAMIN
{

}