<?php

/**
 * SAF_RAZON_MVAMIN
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SAF_RAZON_MVAMIN extends BaseSAF_RAZON_MVAMIN
{
  public function __toString()
  {
    return $this->getRazon();
  }
}