<?php

/**
 * SAF_R1000_MVAMINTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_R1000_MVAMINTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_R1000_MVAMINTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_R1000_MVAMIN');
    }
}