<?php

/**
 * SAF_MINUTATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_MINUTATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_MINUTATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_MINUTA');
    }
    
    /**
     * Misma documentación. Solo se le agrego orderBy
     */
    public function findAll($hydrationMode = null)
    {
      return $this->createQuery('dctrn_find')
              ->orderBy('created_at desc')
              ->execute(array(), $hydrationMode);
    }
}