<?php

/**
 * SAF_VARIOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_VARIOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_VARIOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_VARIO');
    }
}