<?php

/**
 * SAF_UNIDAD_EQUIPOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_UNIDAD_EQUIPOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_UNIDAD_EQUIPOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_UNIDAD_EQUIPO');
    }
   
    /**
     * Misma definición del método sobrescrito (findAll). Solo se le agregó el 
     * order by y que solo traiga los pertenecientes a un departamento.
     */
    public function findAll($hydrationMode = null)
    {
      return $this->createQuery('dctrn_find')
              ->where('departamento = ?','IOD')
              ->orderBy('nombre')
              ->execute(array(), $hydrationMode);
    }
}