<?php

/**
 * SAF_UNIDAD_EQUIPOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_UNIDAD_EQUIPOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_UNIDAD_EQUIPOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_UNIDAD_EQUIPO');
    }
   
    /**
     * Misma definición de la sobrescritura. Solo se le agregó el order by
     */
    public function findAll($hydrationMode = null)
    {
      return $this->createQuery('dctrn_find')->orderBy('nombre')->execute(array(), $hydrationMode);
    }
}