<?php

/**
 * SAF_FOTOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_FOTOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_FOTOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_FOTO');
    }
}