<?php

/**
 * SAF_TAREA_REALIZADA_COMPTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_TAREA_REALIZADA_COMPTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_TAREA_REALIZADA_COMPTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_TAREA_REALIZADA_COMP');
    }
}