<?php

/**
 * SAF_ASISTENCIA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SAF_ASISTENCIA extends BaseSAF_ASISTENCIA
{

  /**
   * Método sobrescrito que retorna el objeto SAF_PERSONAL de SAF_ASISTENCIA, es 
   * decir, si una persona asistio al comité entonces es retornado el objeto 
   * SAF_PERSONAL para asi obtener todos sus atributos.
   * 
   * @return type
   */
  public function getSAFPERSONAL()
  {
    return Doctrine_Core::getTable('sfGuardUser')->findOneByCi($this->getIdPersonal());
  }

}