<?php

/**
 * SAF_ASISTENCIATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_ASISTENCIATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_ASISTENCIATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_ASISTENCIA');
    }
}