<?php

/**
 * SAF_PERSONALTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_PERSONALTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_PERSONALTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_PERSONAL');
    }
}