<?php

/**
 * SAF_RAZON_MVAMINTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_RAZON_MVAMINTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_RAZON_MVAMINTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_RAZON_MVAMIN');
    }
}