<?php

/**
 * SAF_PERSONALTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_PERSONALTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_PERSONALTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_PERSONAL');
    }
    
    // Misma documentacion del método sobrescrito findAll()
    public function findAll($hydrationMode = null)
    {
      return $this->createQuery('dctrn_find personal')
              ->innerJoin('personal.SAF_UNIDAD_EQUIPO unidad_equipo')
              ->where('unidad_equipo.departamento = ?','IOD')
              ->execute(array(), $hydrationMode);
    }
}