<?php

/**
 * SAF_COMP_UETable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_COMP_UETable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_COMP_UETable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_COMP_UE');
    }
}