<?php

/**
 * SAF_PERSONAL
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Proyecto_SAF
 * @subpackage model
 * @author     Rosman_Torres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SAF_PERSONAL extends BaseSAF_PERSONAL
{
  /**
   * Método sobrescrito que retorna el objeto SAF_UNIDAD_EQUIPO de SAF_PERSONAL,
   * es decir, retorna la unidad a la que pertence la persona.
   * 
   * @return type
   */
  public function getSAFUNIDADEQUIPO()
  {
    return Doctrine_Core::getTable('SAF_UNIDAD_EQUIPO')->find($this->getIdUe());
  }
}