<?php

/**
 * SAF_EVENTO_RAZONTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SAF_EVENTO_RAZONTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SAF_EVENTO_RAZONTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SAF_EVENTO_RAZON');
    }
}