<?php

/**
 * UNIDAD_SOPORTESTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UNIDAD_SOPORTESTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UNIDAD_SOPORTESTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UNIDAD_SOPORTES');
    }
}