# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Las rutas son llamadas con el helper url_for de la siguiente manera:
# echo url_for('@mostrar_agenda?id=1') 
# echo url_for('agenda_convocatoria/show?id=1')
# Ambas llamadas dan lo mismo, solo que la primera busca la ruta directamente
# y la segunda busca ruta a ruta hasta encontrar una que coincida con la accion
# y los parametros enviados.

# Rutas para el módulo de agenda_convocatoria
index_agenda:
  url: /agenda_convocatoria
  param: { module: agenda_convocatoria, action: listar }
  
mostrar_agenda:
  url: /agenda_convocatoria/mostrar/:id
  param: { module: agenda_convocatoria, action: mostrar }

colocar_pendiente_agenda:
  url: /agenda_convocatoria/mostrar/:id/cambiar_status
  param: { module: agenda_convocatoria, action: colocarPendiente }

nueva_agenda:
  url: /agenda_convocatoria/nueva
  param: { module: agenda_convocatoria, action: nueva }
  
vista_preliminar_agenda:
  url: /agenda_convocatoria/vista_preliminar
  param: { module: agenda_convocatoria, action: vistaPreliminar }
  
filtrar_agenda:
  url: /agenda_convocatoria/nueva/eventos_encontrados
  param: { module: agenda_convocatoria, action: filtrar }
  
agregar_eventos_agenda:
  url: /agenda_convocatoria/nueva/eventos_encontrados/agregar_eventos_agenda
  param: { module: agenda_convocatoria, action: agregarEventosALaAgenda }
  
guardar_agenda:
  url: /agenda_convocatoria/nueva/guardar
  param: { module: agenda_convocatoria, action: guardarAgenda }

# Rutas para el módulo de convocatoria
index_convocatoria:
  url: /convocatoria
  param: { module: convocatoria, action: listar }
  
nueva_convocatoria:
  url: /convocatoria/nueva
  param: { module: convocatoria, action: nueva }
  
mostrar_convocatoria:
  url: /convocatoria/mostrar/:id
  param: { module: convocatoria, action: mostrar }

vista_preliminar_convocatoria:
  url: /convocatoria/vista_preliminar
  param: { module: convocatoria, action: vistaPreliminar }

cargar_agenda:
  url: /convocatoria/nueva/eventos_encontrados_agenda
  param: { module: convocatoria, action: cargarEventosDeAgenda }
  
agregar_eventos_convocatoria:
  url: /convocatoria/nueva/eventos_encontrados_agenda/agregar_eventos_a_la_convocatoria
  param: { module: convocatoria, action: agregarEventosALaConvocatoria }
  
guardar_convocatoria:
  url: /convocatoria/nueva/guardar
  param: { module: convocatoria, action: guardarConvocatoria }
 
cambiar_status_convocatoria:
  url: /convocatoria/cambiar_status
  param: { module: convocatoria, action: cambiarStatus }
  
# Rutas para el módulo de minuta
index_minuta:
  url: /minuta
  param: { module: minuta, action: listar }  
  
nueva_minuta:
  url: /minuta/nueva
  param: { module: minuta, action: nueva }

inicio_desarrollo:
  url: /minuta/desarrollo/:id
  param: { module: minuta, action: inicioDesarrollo }
  
desarrollar_evento:
  url: /minuta/desarrollo/desarrollar_evento/:id/:id_convocatoria
  param: { module: minuta, action: desarrollarEvento }
  
procesar_evento_minuta:
  url: /minuta/procesar_evento/:id/:id_convocatoria
  param: { module: minuta, action: procesarEvento}
  
agregar_razones_mvamin:
  url: /minuta/razones_mvamin
  param: { module: minuta, action: razonesMVAmin }
  
agregar_unidad_equipo:
  url: /minuta/unidad_equipo
  param: { module: minuta, action: unidadEquipo }
  
agregar_asistentes:
  url: /minuta/personal
  param: { module: minuta, action: personal }
    
visualizar_minuta:
  url: /minuta/PDF/:id
  param: { module: minuta, action: visualizarMinuta }
  
guardar_status_minuta:
  url: /minuta/guardar_status/:id
  param: { module: minuta, action: guardarStatusMinuta }
  
finalizar_minuta:
  url: /minuta/finalizar/:id
  param: { module: minuta, action: finalizarMinuta}
  
# Rutas para el módulo de estadisticas e indicadores
index_estadisticas_indicadores:
  url: /estadisticas_e_indicadores_de_gestion
  param: { module: estadisticas_indicadores, action: charts }
  
# Rutas para el módulo de seguimiento y control  
index_seguimiento_control:
  url: /seguimiento_control
  param: { module: seguimiento_control, action: inicio }
  
filtrar_compromisos:
  url: /seguimiento_control/filtrar
  param: { module: seguimiento_control, action: filtrar }
  
registrar_acciones_compromisos:
  url: /seguimiento_control/registrar_acciones_compromiso/:id_comp
  param: { module: seguimiento_control, action: registrarAccionesComprimiso }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
