<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/23 13:07:07
sfConfig::add(array(
  'mod_agenda_convocatoria_enabled' => true,
  'mod_agenda_convocatoria_view_class' => 'sfPHP',
));
