<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    // Misma documentacion del método sobrescrito findAll()
    public function findAll($hydrationMode = null)
    {
      return $this->createQuery('dctrn_find user')
              ->innerJoin('user.SAF_UNIDAD_EQUIPO unidad_equipo')
              ->where('unidad_equipo.departamento = ?','IOD')
              ->execute(array(), $hydrationMode);
    }
}