all:
  schema_saf:
    class: sfDoctrineDatabase
    param:
      dsn: oracle://SAF:safdes@10.2.101.107/(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.2.101.107)(PORT=1521)))(CONNECT_DATA=(SID=OPCCODUP)))
  schema_siod:
    class: sfDoctrineDatabase
    param:
      dsn: oracle://SIOD:siodd@10.2.101.107/(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.2.101.107)(PORT=1521)))(CONNECT_DATA=(SID=OPCCODUP)))
  schema_simip:
    class: sfDoctrineDatabase
    param:
      dsn: oracle://SIMIP:simipd@10.2.101.107/(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.2.101.107)(PORT=1521)))(CONNECT_DATA=(SID=OPCCODUP)))