<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/24 12:42:42
sfConfig::add(array(
  'mod_agenda_convocatoria_enabled' => true,
  'mod_agenda_convocatoria_view_class' => 'sfPHP',
));
