SAF_AGENDA_CONVOCATORIA:
  connection: schema_saf
  tableName: SAF_AGENDA_CONVOCATORIA
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, primary: true, sequence: true }
    departamento: { notnull: true, type: string(50) }     
    observacion: { notnull: false, type: string(1000) }
    pendiente: { notnull: true, type: integer }
  relations:
    SAF_EVENTO:
      local: id
      foreign: id_agenda
      type: many
      
SAF_ASISTENCIA:
  connection: schema_saf
  tableName: SAF_ASISTENCIA
  columns:
    id_convocatoria: { type: integer, primary: true }
    id_personal: { type: integer, primary: true }
  relations:
    SAF_CONVOCATORIA_CAF:
      local: id_convocatoria
      foreign: id
      type: one
    SAF_PERSONAL:
      local: id_personal
      foreign: ci
      type: one
      
SAF_COMP_UE:
  connection: schema_saf
  tableName: SAF_COMP_UE
  columns:
    id: { type: integer, primary: true, sequence: true }
    id_compromiso: { notnull: true, type: integer }
    id_ue: { notnull: true, type: integer }
  relations:
    SAF_VARIO:
      local: id_compromiso
      foreign: id
      type: one
    SAF_UNIDAD_EQUIPO:
      local: id_ue
      foreign: id
      type: one
    SAF_TAREA_REALIZADA_COMP:
      local: id
      foreign: id_comp_ue
      type: many
      
SAF_CONVOCATORIA_CAF:
  connection: schema_saf
  tableName: SAF_CONVOCATORIA_CAF
  actAs: { Timestampable: ~ }
  columns:
    id: {type: integer, primary: true, sequence: true }
    asunto: { notnull: true, type: string(100) }
    fecha: { notnull: true, type: timestamp(7) }
    hora_ini: { notnull: true, type: string(7) }
    hora_fin: { notnull: true, type: string(7) }
    lugar: { notnull: true, type: string(100) }
    status: { notnull: true, type: string(50) }
    motivo_suspencion: { notnull: false, type: string(1000) }
    observacion: { notnull: false, type: string(1000) }
    c_caf: { notnull: false, type: string(100) }
  relations:
    SAF_EVENTO:
      local: id
      foreign: id_convocatoria
      type: many
    SAF_ASISTENCIA:
      local: id
      foreign: id_convocatoria
      type: many
    
SAF_EVENTO:
  connection: schema_saf
  tableName: SAF_EVENTO
  columns:
    id: { type: integer, primary: true, sequence: true }
    descripcion: { type: string(500) }
    id_agenda: { notnull: false, type: integer }
    id_convocatoria: { notnull: false, type: integer }    
    status: { notnull: false, type: string(50) }
    c_evento_t: { notnull: false, type: integer }
    c_evento_d: { notnull: false, type: integer }
    f_hora_ini: { type: timestamp(7) }
    f_hora_rep: { type: timestamp(7) }
    region: { type: string(100) }
    circuito: { type: string(100) }
    cod_nivel: { type: integer }
    kva_int: { type: integer }
    mva_min: { type: integer }
    num_averia: { type: integer }
    desc_averia: { type: string(4000) }
    tipo_falla: { type: string(50) }
    operador: { type: string(50) }
    cuadrilla: { type: string(50) }
    climatologia: { type: string(50) }
    trabajo_realizado: { type: string(4000) }
    num_roe: { type: integer }
    programador: { type: string(50) }
    operador_resp: { type: string(50) }
  relations:
    SAF_AGENDA_CONVOCATORIA:
      local: id_agenda
      foreign: id
      type: one
    SAF_CONVOCATORIA_CAF:
      local: id_convocatoria
      foreign: id
      type: one
    SAF_VARIO:
      local: id
      foreign: id_evento
      type: many
    SAF_FOTO:
      local: id
      foreign: id_evento
      type: many
    SAF_EVENTO_RAZON:
      local: id
      foreign: id_evento
      type: many
      
SAF_FOTO:
  connection: schema_saf
  tableName: SAF_FOTO
  columns:
    id: { type: integer, primary: true, sequence: true }
    titulo: { notnull: true, type: string(100) }
    dir: { notnull: true, type: string(100) }
    id_evento: { notnull: false, type: integer }
    sub_titulo: { notnull: false, type: string(100) }
  relations:
    SAF_EVENTO:
      local: id_evento
      foreign: id
      type: one

SAF_PERSONAL:
  connection: schema_saf
  tableName: SAF_PERSONAL
  columns:
    ci: { type: integer, primary: true }
    id_ue: { notnull: true, type: integer }
    nombre: { notnull: false, type: string(50) }
    apellido: { notnull: false, type: string(50) }
    correo: { notnull: false, type: string(50) }
  relations:
    SAF_UNIDAD_EQUIPO:
      local: id_ue
      foreign: id
      type: one
    SAF_ASISTENCIA:
      local: ci
      foreign: id_personal
      type: many
      
SAF_RAZON_MVAMIN:
  connection: schema_saf
  tableName: SAF_RAZON_MVAMIN
  columns:
    id: { type: integer, primary: true, sequence: true }
    razon: { notnull: true, type: string(50), unique: true }
  relations:
    SAF_EVENTO_RAZON:
      local: id
      foreign: id_razon
      type: many
      
SAF_EVENTO_RAZON:
  connection: schema_saf
  tableName: SAF_EVENTO_RAZON
  columns:
    id_evento: { notnull: true, type: integer, primary: true }
    id_razon: { notnull: true, type: integer, primary: true }
    mva_min: { notnull: true, type: integer }
  relations:
    SAF_EVENTO:
      local: id_evento
      foreign: id
      type: one
    SAF_RAZON_MVAMIN:
      local: id_razon
      foreign: id
      type: one
      
SAF_TAREA_REALIZADA_COMP:
  connection: schema_saf
  tableName: SAF_TAREA_REALIZADA_COMP
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, primary: true, sequence: true }
    id_comp_ue: { notnull: true, type: integer }
    descripcion: { notnull: false, type: string(1000) }
  relations:
    SAF_COMP_UE:
      local: id_comp_ue
      foreign: id
      type: one
      
SAF_UNIDAD_EQUIPO:
  connection: schema_saf
  tableName: SAF_UNIDAD_EQUIPO
  columns:
    id: { type: integer, primary: true, sequence: true }
    nombre: { notnull: true, type: string(50) }
    correo: { notnull: true, type: string(50) }
  relations:
    SAF_PERSONAL:
      local: id
      foreign: id_ue
      type: many
    SAF_COMP_UE:
      local: id
      foreign: id_ue
      type: many
      
SAF_VARIO:
  connection: schema_saf
  tableName: SAF_VARIO
  actAs: { Timestampable: ~ }
  columns:
    id: { type: integer, primary: true, sequence: true }
    id_evento: { notnull: true, type: integer }
    tipo: { notnull: true, type: string(50) }
    descripcion: { notnull: true, type: string(4000) }
    f_duracion_estimada: { notnull: false, type: timestamp(7) }
    status: { notnull: false, type: string(50) }
    titulo: { notnull: false, type: string(100) }
  relations:
    SAF_EVENTO:
      local: id_evento
      foreign: id
      type: one
    SAF_COMP_UE:
      local: id
      foreign: id_compromiso
      type: many
      
# A partir de aqui son tablas ya creadas por CORPOELEC en el schema SIOD
AVERIA:
  connection: schema_siod
  tableName: AVERIA
  columns:
    num_averia: { type: integer(9), primary: true }
    descripcion: { notnull: false, type: string(4000) }
    
INTERRUPCIONES:
  connection: schema_siod
  tableName: INTERRUPCIONES
  columns:
    num_f328: { type: integer(7), primary: true }
    nivel_sistema: { notnull: true, type: integer(1) }
    cod_sistema: { notnull: true, type: integer(5) }
    fecha_hora_ini: { notnull: true, type: timestamp(7) }
    kva_interrump: { notnull: true, type: integer(7) }
    mvamin: { notnull: true, type: decimal(7) }
    cod_causa: { notnull: true, type: integer(3) }
    distrito: { notnull: true, type: integer(2) }
    num_proposicion: { type: integer(11) }
    trabajo_realizado: { type: string(2000) }
    climatologia: { type: integer(1) }
    num_roe: { type: integer(7) }
    num_averia: { type: integer(9) }

CRONOLOGIA:
  connection: schema_siod
  tableName: CRONOLOGIA
  columns:
    num_f328: { type: integer(7), primary: true }
    fecha_reparacion: { notnull: true, type: timestamp(7) }
    resp_mesa_rep: { notnull: true, type: string(5) }

CRONOLOGIA_CUADRILLA_INT:
  connection: schema_siod
  tableName: CRONOLOGIA_CUADRILLA_INT
  columns:
    num_f328: { type: integer(7), primary: true }
    cod_cuad_cont: { type: string(11), primary: true }

# A partir de aqui son tablas ya creadas por CORPOELEC en el schema SIMIP
OPERADORES:
  connection: schema_simip
  tableName: OPERADORES
  columns:
    cod_operador: { type: integer(8), primary: true }
    desc_operador: { notnull: true, type: string(30) }

HIST_PROPOSICIONES:
  connection: schema_simip
  tableName: HIST_PROPOSICIONES
  columns:
    cod_proposicion: { notnull: true, type: integer(6), primary:true }
    oper_cod_operador_resp: { notnull: true, type: integer(8) }
    oper_cod_operador_asig: { notnull: true, type: integer(8) }

CIRCUITOS:
  connection: schema_simip
  tableName: CIRCUITOS
  columns:
    cod_cto: { type: integer(4), primary: true }
    bar_cod_barra: { notnull: true, type: integer(4) }
    desc_cto: { notnull: true, type: string(30) }
